version: '3.8'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  springboot:
    build: ./springboot
    depends_on:
      - database
    ports:
      - "8080:8080"
  nextjs:
    image: node:14
    working_dir: /app
    volumes:
      - ./nextjs:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - springboot
